### ISSUE TITLE
Make it easier to develop tests when crayon is in use

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1053] opened 2020-06-23 18:21 UTC
This happens a lot when I'm developing tests that inspect a crayon-style message:

```
> test_that("check_uses_github_actions() can throw error", {
+   create_local_package()
+   expect_error(
+     check_uses_github_actions(),
+     "Do you need to run `use_github_actions()`?",
+     fixed = TRUE, class = "usethis_error"
+   )
+ })
Error: Test failed: 'check_uses_github_actions() can throw error'
* `check_uses_github_actions()` threw an error with unexpected message.
Expected match: "Do you need to run `use_github_actions()`?"
Actual message: "Cannot detect that package \033[34m'testpkg900b3aef5ec1'\033[39m already uses GitHub Actions.\nDo you need to run \033[90m`use_github_actions()`\033[39m?"
Backtrace:
 1. testthat::expect_error(...)
 6. usethis::check_uses_github_actions()
 7. usethis::ui_stop("\n    Cannot detect that package {ui_value(project_name(base_path))} already \\\n    uses GitHub Actions.\n    Do you need to run {ui_code('use_github_actions()')}?\n    ") UsersjennyrrrusethisRgithub-actions.R:55:2
Backtrace:
    █
 1. └─testthat::test_that(...)
 2.   └─testthat:::test_code(desc, code, env = parent.frame())
 3.     └─get_reporter()$end_test(context = get_reporter()$.context, test = test)
```

In "production", this won't be a problem because the option `crayon.enabled` will be `FALSE` and the message won't contain the escapes.

Yes, I can always set `options("crayon.enabled" = FALSE)` in the session I'm working in, but then I lose lots of *nice* uses of crayon.

Is there any reason to not strip ANSI escapes from all messages inspected in functions like `expect_error()`?

**Comment by hadley** [comment] 2020-06-23 18:27
Duplicate of #1044. @gaborcsardi and I were just talking about doing what you propose 😄

**Closed by hadley** 2020-06-23 18:27 UTC
