### ISSUE TITLE
Clarification requested on docs about "special files"

### ISSUE THREAD

**Issue by jamieRowen** [r-lib/testthat#1675] opened 2022-09-06 13:20 UTC
I saw #1638 requesting better documentation, but am not aware what the documentation at the time of writing of that issue was. 

At present it says:

```
There are two other types of special file that we no longer recommend using:

* Helper files start with helper and are executed before tests are run. They're also loaded by devtools::load_all(), so there's no real point to them and you should just put your helper code in R/.

* Teardown files start with teardown and are executed after the tests are run. Now we recommend interleave setup and cleanup code in setup- files, making it easier to check that you automatically clean up every mess that you make.

All other files are ignored by testthat.
```

I am intrigued as to the reasoning behind why it is not recommended to use helper files, or perhaps why it is recommended to instead prefer putting the source for these in R/

To me this is a little confusing, as the source code for my package and the testing separation becomes more blurred. In addition a code coverage report which I might care about for my source code would also cover the helper functions that I am writing purely for the purpose of testing and subsequently generating said report. 

Is there something I am missing about this suggestion?

**Comment by hadley** [comment] 2022-09-19 19:35
Duplicate of #1638. We don't not recommended them any more 😆

**Closed by hadley** 2022-09-19 19:35 UTC
