### ISSUE TITLE
character context issue 

### ISSUE THREAD

**Issue by neonira** [r-lib/testthat#1248] opened 2020-11-27 09:34 UTC
When running tests using **testthat::file** in the __RStudio__ console, tests works fine. 

Running the same test using shortcut __CTRL + SHIFT + T__, runs the test and it systematically fails. 
I instrumented the test to get some contextual information to be able to at least identify the most probable issue source. Refer to attached picture. 

It shows at north east the test file used, at south east the console test run results and at north west the test pane results.
Red arrows points the main issue. **Character order in console and in test context does not appear to be the same**. I deal only with ascii compatible characters. See **sessionInfo()** output below for contextual and system information.  

Not only, I wonder why, but more surely, I guess this is simply wrong. 

Any suggestion to circumvent this ?
![testhat_issue - 1](https://user-images.githubusercontent.com/37214634/100433506-7a02cc80-309b-11eb-8f3b-812072c7367e.jpg)

<pre>
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] testthat_3.0.0           lubridate_1.7.9.2        crayon_1.3.4             data.table_1.13.2       
 [5] wyz.string.human_1.1.3   wyz.code.release_4.1.9   wyz.code.ops_3.3.7       wyz.filesystem.ops_1.1.5
 [9] wyz.string.ops_1.1.5     wyz.data.input_1.1.6    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       rstudioapi_0.13  rematch2_2.1.2   magrittr_2.0.1   hms_0.5.3        pkgload_1.1.0    R6_2.5.0        
 [8] rlang_0.4.9      fansi_0.4.1      tools_4.0.3      waldo_0.2.3      cli_2.2.0        withr_2.3.0      ellipsis_0.3.1  
[15] rprojroot_2.0.2  assertthat_0.2.1 tibble_3.0.4     lifecycle_0.2.0  readr_1.4.0      vctrs_0.3.5      glue_1.4.2      
[22] diffobj_0.3.2    compiler_4.0.3   pillar_1.4.7     desc_1.2.0       generics_0.1.0   pkgconfig_2.0.3 
</pre>

**Comment by gaborcsardi** [comment] 2020-11-27 09:38
You would have to show us a reproducible example, but I think this might be a duplicate of #1181

**Comment by neonira** [comment] 2020-11-27 11:45
Your suggestion https://github.com/r-lib/testthat/issues/1181 is useful.

Sticking to **pure C locale** and **US_ASCII** solves the issue. 
Thanks for suggestion

**Comment by neonira** [comment] 2020-11-27 11:46
Solved on my side by enforcing strict US_ASCII compliance.

**Closed** 2020-11-27 11:46 UTC
