### ISSUE TITLE
expect_error class message is confusing

### ISSUE THREAD

**Issue by cimentadaj** [r-lib/testthat#931] opened 2019-08-30 10:26 UTC
```r
library(rlang)
library(testthat)
#> 
#> Attaching package: 'testthat'
#> The following objects are masked from 'package:rlang':
#> 
#>     is_false, is_null, is_true

my_error <- error_cnd("http_404/http_403/error",
                      message = "This is an error")
expect_error(
  cnd_signal(my_error),
  regexp = "This is an error",
  fixed = TRUE
)
#> Warning: `cnd_signal(my_error)` generated a condition with class http_404/http_403/error/rlang_error/error/condition.
#> It is less fragile to test custom conditions with `class`
```

I was very confused on what the class specification actually meant. Was it a regex to match all class collapsed? I think it would be more intuitive to paste it as a vector. Such as: `generated a conditions with class: c("http_404", "http_403", "error", "rlang_error", "error", "condition")`

Otherwise, I think users might suppose that the class argument is a regex matching
for that specific string ("http_404/http_403/error/rlang_error/error/condition")

**Comment by hadley** [comment] 2019-10-13 14:13
Duplicate of #918

**Comment by hadley** [comment] 2019-10-13 14:13
Thanks for the idea about how print it! I'll implement that shortly.

**Closed by hadley** 2019-10-13 14:13 UTC
