### ISSUE TITLE
Is auto-labeling overdoing it?  Bug in  `is_call_infix()` 

### ISSUE THREAD

**Issue by mmaechler** [r-lib/testthat#1495] opened 2021-11-23 17:21 UTC
For me, `R CMD check lme4` has started to fail, because I do have
the  `_R_CHECK_LENGTH_1_LOGIC2_`  env.variable set to `verbose`.

An example not needing `lme4`:
```
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_" = "verbose")
fit <- lm(sr ~ pop15, data = LifeCycleSavings)
expect_is(stats::anova(update(fit, . ~ . + pop75),
                                    update(fit, . ~ . + pop75 + ddpi)),  
               "anova")
```
produces 
```
 ----------- FAILURE REPORT -------------- 
 --- failure: length > 1 in coercion to logical ---
 --- srcref --- 
: 
 --- package (from environment) --- 
testthat
 --- call from context --- 
is_call_infix(x)
 --- call from argument --- 
name %in% base || grepl("^%.*%$", name)
 --- R stacktrace ---
where 1: is_call_infix(x)
where 2: expr_label(expr)
where 3: label %||% expr_label(expr)
where 4: quasi_label(enquo(object), label, arg = "object")
where 5: expect_is(stats::anova(update(fit, . ~ . + pop75), update(fit, 
    . ~ +ddpi + pop75)), "anova")

 --- value of length: 3 type: logical ---
[1]  TRUE FALSE FALSE
 --- function from context --- 
function (x) 
{
    if (!is_call(x, n = 2)) {
        return(FALSE)
    }
    name <- as.character(x[[1]])
    base <- c(":", "::", ":::", "$", "@", "^", "*", "/", "+", 
        "-", ">", ">=", "<", "<=", "==", "!=", "!", "&", "&&", 
        "|", "||", "~", "<-", "<<-")
    name %in% base || grepl("^%.*%$", name)
}
<bytecode: 0x1e011680>
<environment: namespace:testthat>
 --- function search by body ---
Function is_call_infix in namespace testthat has this body.
 ----------- END OF FAILURE REPORT -------------- 
Error in name %in% base || grepl("^%.*%$", name) : 
  'length(x) = 3 > 1' in coercion to 'logical(1)'

Enter a frame number, or 0 to exit   

1: expect_is(stats::anova(update(fit, . ~ . + pop75), update(fit, . ~ +ddpi + pop75)), "an
2: quasi_label(enquo(object), label, arg = "object")
3: label %||% expr_label(expr)
4: expr_label(expr)
5: is_call_infix(x)

Selection: 4
Called from: is_call_infix(x)
Browse[1]> ls.str()
chr :  chr [1:2] "stats::anova(update(fit, . ~ . + pop75), update(fit, . ~ +ddpi + " ...
x :  language stats::anova(update(fit, . ~ . + pop75), update(fit, . ~ +ddpi + pop75))
Browse[1]> 
```
and indeed, the `is_call_infix()` function makes wrong assumptions, treating  `stats::anova` as a symbol and thus its `name` then is of length 3.  

To me, this smells much like "overdoing it':   
Everything works fine (still when having set the env.var), if I compute the two models first and also if I compute the anova first:

Semantically equivalent versions work fine  -- if only you could refrain from NSE (non-standard evaluation) -- 
These two "equivalent" versions have no problem:
```
## version 2 :
fit <- lm(sr ~ pop15, data = LifeCycleSavings)
m1 <- update(fit, . ~ . + pop75)
m2 <- update(fit, . ~ . + pop75 + ddpi)
expect_is(stats::anova(m1, m2), "anova") # no problem
```
or also

```
## version 3 :
fit <- lm(sr ~ pop15, data = LifeCycleSavings)
aa <- stats::anova(update(fit, . ~ . + pop75),
                   update(fit, . ~ . + pop75 + ddpi))
expect_is(aa, "anova") # no problem
```

**Comment by hadley** [comment] 2021-11-24 17:03
Duplicate of #1472 — rlang release is taking longer than expected, so we'll fix temporarily in the near future.

**Closed by hadley** 2021-11-24 17:03 UTC
