### ISSUE TITLE
in dev testthat `expect_equivalent()` compares class names

### ISSUE THREAD

**Issue by gergness** [r-lib/testthat#1014] opened 2020-04-17 01:12 UTC
Was hoping to use the dev version of test for some other recent changes, but the new `expect_equivalent()` changes behavior on S3 class names. They did not used to be compared between objects, but now they are. Is this intentional? 

```r
x <- list(a = 1)
class(x) <- "class1"

y <- list(a = 1)

testthat::expect_equivalent(x, y)
# Returns nothing in CRAN testthat

# But on dev version (testthat r-lib/testthat@f0b820c & waldo 0.1.0)
#> Error: `actual` (`x`) not equal to `expected` (`y`).
#> 
#> `actual` is an S3 object of class <class1>
#> `expected` is a list
```

(the Waldo output does look great though!)
Thank you!

**Comment by gergness** [comment] 2020-04-17 01:30
Another change that caught me was that `expect_equivalent` used to have a tolerance set by default but no longer does

**Comment by hadley** [comment] 2020-04-18 14:49
Duplicate of https://github.com/r-lib/waldo/issues/26

**Closed by hadley** 2020-04-18 14:49 UTC
