### ISSUE TITLE
Unhelpful message from expect_equal when objects differ

### ISSUE THREAD

**Issue by rillig** [r-lib/testthat#952] opened 2019-10-17 03:12 UTC
~~~r
test_that('mismatch gives error without any hints', {
    actual <- list('frist', 'second')
    expected <- list('first', 'second')

    expect_equal(actual, expected)
})
~~~

When I run this test, the output is:

~~~text
Fehler: Test failed: 'mismatch gives error without any hints'
* `actual` not equal to `expected`.
Component 1: 1 string mismatch
Ausführung angehalten
~~~

The message that "actual not equal to expected" doesn't help me at all. I already know this, otherwise the test wouldn't have failed.

It's easy to see the difference between the objects by printing them both and making a diff of the output.

Why doesn't testthat do exactly this? Or, alternatively, navigate the object structure to find the first few differences?

Curiously, in a slight variation of the above code that I cannot reproduce anymore, I think I saw a really helpful error message, saying "frist != first". That is much more to the point than a mere "Component 1: 1 string mismatch".

**Comment by cderv** [comment] 2019-10-17 05:48
I don't think it will answer your question but know that [testthat supports quasiquotation](https://testthat.r-lib.org/news/index.html#quasiquotation-support) (from rlang) and that it helps with clarifying the message.
With you example 
``` r
library(testthat)      
test_that('mismatch gives error without any hints', {
  actual <- list('frist', 'second')
  expected <- list('first', 'second')
  
  expect_equal(!!actual, !!expected)
})
#> Error: Test failed: 'mismatch gives error without any hints'
#> * list("frist", "second") not equal to list("first", "second").
#> Component 1: 1 string mismatch
```
There is still no diff though. 

Hope it helps.

**Comment by hadley** [comment] 2019-10-17 13:58
@cderv thanks for the useful suggestions!

Otherwise this is a duplicate of #447 — fixing this problem well requires a bunch of work, which we will tackle at some point in the future.

**Closed by hadley** 2019-10-17 13:58 UTC
