### ISSUE TITLE
expect_equal documentation unclear

### ISSUE THREAD

**Issue by willemvdb42** [r-lib/testthat#801] opened 2018-09-24 14:02 UTC
I find that the documentation for `expect_equal` is unclear. In a nutshell my argument is that `expect_equal` often works in complex ways that are not at all intuitively clear. This complexity if twofold: 

1. `all.equal` itself works in complex ways that are poorly documented
2. `expect_equal` is not a simple application of `all.equal`. Sometimes it does something distinctly different.

All this is best illustrated with some examples.

**Example 1**
The first difficulty is that `all.equal` itself works in complex ways. (This example is based on [stackoverflow](https://stackoverflow.com/questions/15334701/how-does-the-tolerance-parameter-of-all-equal-work).) `all.equal` can test for equality in different ways: if `target` is greater than `tolerance` it will use a relative error, but if `target` is smaller or equal to `tolerance` is will use an absolute error:
```
# The check performed by all.equal depends on which is larger: tolerance or target
all.equal(0.01, 4, tolerance = 0.01) # uses mean absolute difference
all.equal(0.01, 4, tolerance = 0.00999) # uses mean relative difference
```
This behaviour is mentioned only very briefly in the details of that function. The arguments section for `all.equal` simply states "tolerance - numeric ≥ 0. Differences smaller than tolerance are not reported. The default value is close to 1.5e-8." which seems to (incorrectly!) imply absolute differences are always used.

My issue here is that `all.equal` at least mentions this in the output of the function (it mentions whether it used an absolute or relative difference). `expect_equal` returns an output which makes no mention of the fact that an entirely different algorithm was used.
```
expect_equal(0.01, 4, tolerance = 0.01)
expect_equal(0.01, 4, tolerance = 0.00999)
```

**Example 2**
`expect_equal` sometimes does not even do the same thing as `all.equal`: 
```
all.equal(.51, .24, tolerance = 0.5) # this reports: "Mean relative difference: 0.5294118"
expect_equal(.51, .24, tolerance = 0.5) # this does not throw an error
```
Unless I'm missing something here, this is a discrepancy between `all.equal` and `expect_equal`. Again this is undocumented.

**Example 3**
It gets even more complicated when using vectors of multiple elements. The output of `expect_equal` seems to imply an element wise comparison of elements is performed, and all differences larger than `tolerance` are reported. This is not the case. `all.equal` uses a _mean_ difference (absolute or relative, see example 1). Moreover, this mean is not calculated across all elements, but only those elements that are not NA, and for which `target` is not exactly equal to `current`. Again this leads to very non-intuitive behaviour.
```
all.equal(c(10, 1e15), c(0, 1e15)) # 1e15 is eliminated because exactly equal in both cases
all.equal(c(10, 1e15), c(0, 1e15 + 1)) # A small difference (some noise?) changes this
```
This means that the errors that are reported depend not only on an element wise comparison but also on other elements in both vectors. `expect_equal` has the same behaviour.
```
expect_equal(c(10, 1e15), c(0, 1e15))
expect_equal(c(10, 1e15), c(0, 1e15 + 1))
```
Whether an element in vector `object` at index `i` is to be deemed equal or unequal to its counterpart in `expected`, depends not only on those two elements at index `i` but on all other elements of both vectors! Again this fact is obscured by the fact that `expect_equal` seems to imply element wise comparison in its output.

If a difference of 10 seems irrelevant compared to 1e15, then consider the following:
```
all.equal(c(10, 1000), c(0, 1000), tolerance = 0.5) # not equal
all.equal(c(10, 1000), c(0, 1001), tolerance = 0.5) # equal
expect_equal(c(10, 1000), c(0, 1000), tolerance = 0.5) # not equal
expect_equal(c(10, 1000), c(0, 1001), tolerance = 0.5) # equal
```

**Suggestion**
At the very least please expand the documentation for `expect_equal`.

- Highlight these problems clearly with examples
- Clearly mention that either absolute or relative difference may be used, depending on input
- Clearly mention that `expect_equal` is _not_ an element wise comparison, but uses a mean over all elements
- Highlight how and where `expect_equal` works differently from `all.equal` and why

I think many users (myself included) will automatically assume that that `expect_equal` does an element wise comparison, and then throws an error if at least one difference is larger than `tolerance`. As was shown above, this is not at all the case. Finding this out is currently not easy, and requires in-depth knowledge of the underlying function `all.equal`.

(If I may be so bold I would like to politely add that, given its complexity, the `expect_equal` function is, in my personal opinion, not at all intuitive in its current form. Even extensive documentation will not change that. As it is the aim of the `testthat` package to make testing easy and intuitive, might I suggest changing it so that it does not use the very non-intuitive `all.equal` function? I think something simple is enough: just an element-wise comparison of elements where an error is thrown if any difference is larger than `tolerance`. Perhaps an argument `relativeDifference = FALSE` could be added. This is but a humble suggestion. I will settle for clear documentation ;-).)

**Comment by hadley** [comment] 2019-03-28 22:16
I think this is basically a duplicate of #447 — comparing objects is one of the most important parts of testing, and doing it well has grown beyond the scope of a single function (and the wrappers that testthat has evolved) and needs to be pulled out in to a separate package.

**Closed by hadley** 2019-03-28 22:16 UTC
