### ISSUE TITLE
expect_identical: Give more detail if “Objects equal but not identical”

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/testthat#920] opened 2019-08-06 09:27 UTC
I’m having two objects here, and their `str` looks pretty damn identical:

```r
num [1:4, 1:2] -0.36671 0.95184 -0.00208 -0.58305 -0.00574 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:4] "c1" "c2" "c3" "c4"
  ..$ : chr [1:2] "PC1" "PC2"
 num [1:4, 1:2] -0.36671 0.95184 -0.00208 -0.58305 -0.00574 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:4] "c1" "c2" "c3" "c4"
  ..$ : chr [1:2] "PC1" "PC2"
```

So does “Objects equal but not identical” mean they’re `almost.equal`? If not: What’s not identical here? Attributes? If so: Which ones? How do they differ? *Can* anything apart from attributes be non-identical if the objects are equal?

Every single question here should be answered by the output of `expect_identical`.

**Comment by hadley** [comment] 2019-08-12 20:25
This is basically a duplicate of #447 — fixing this problem requires a full rewrite of `all.equal()`

**Closed by hadley** 2019-08-12 20:25 UTC

**Comment by flying-sheep** [comment] 2019-09-18 12:40
Currently I have a test failure with this only on CRAN, not on a local R-devel instance.

How do people cope? Just never use `expect_identical`?

**Comment by hadley** [comment] 2019-09-18 12:49
You might be able to use `lobstr::sxp(x)` or `.Internal(inspect(x))` to figure out the difference.

**Comment by flying-sheep** [comment] 2019-09-18 14:45
Thank you. It shows that #447 is direly needed though!
