### ISSUE TITLE
Different encoding of characters

### ISSUE THREAD

**Issue by mardam** [r-lib/testthat#1125] opened 2020-07-30 16:21 UTC
Hello,

I was faced to the issue that there seems to be a different character encoding within the R console and devtools::test().

When I run the following code snippet in the R console, it passes.

    library(testthat)
    expect_equal(sort(c("a", "A")),  c("a", "A"))

However, when running with devtools::test(), I get the following failure:

> sort(c("a", "A")) not equal to c("a", "A").
2/2 mismatches
x[1]: "A"
y[1]: "a"
>
>x[2]: "a"
y[2]: "A"

Sessioninfo:

> R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS
> 
> Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
> 
> locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
[1] testthat_2.3.2
> 
> loaded via a namespace (and not attached):
[1] compiler_4.0.2 magrittr_1.5   R6_2.4.1       tools_4.0.2    rlang_0.4.6

**Comment by gaborcsardi** [comment] 2020-07-30 16:24
This is a duplicate of #1076 I believe.

**Closed** 2020-07-30 16:41 UTC
