### ISSUE TITLE
Installation error: invalid token in expression

### ISSUE THREAD

**Issue by sigmafelix** [r-lib/testthat#1244] opened 2020-11-24 15:29 UTC
Hello, I tried to install `testthat` in my machine, but it prints errors as below:

```
* installing *source* package ‘testthat’ ...
file ‘inst/include/testthat.h’ has the wrong MD5 checksum
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT  -I/usr/local/include   -fPIC  -g -O2  -c test-catch.cpp -o test-catch.o
test-catch.cpp:19:5: error: invalid token in expression
    expect_true((4 + 4) == 8);
    ^
../inst/include/./testthat/testthat.h:175:22: note: expanded from macro 'expect_true'
# define expect_true CATCH_CHECK
                     ^
../inst/include/./testthat/vendor/catch.h:11377:29: note: expanded from macro 'CATCH_CHECK'
#define CATCH_CHECK( expr ) INTERNAL_CATCH_TEST( "CATCH_CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
                            ^
../inst/include/./testthat/vendor/catch.h:2207:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:19:5: error: invalid operand
    expect_true((4 + 4) == 8);
    ^
../inst/include/./testthat/testthat.h:175:22: note: expanded from macro 'expect_true'
# define expect_true CATCH_CHECK
                     ^
../inst/include/./testthat/vendor/catch.h:11377:29: note: expanded from macro 'CATCH_CHECK'
#define CATCH_CHECK( expr ) INTERNAL_CATCH_TEST( "CATCH_CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
                            ^
../inst/include/./testthat/vendor/catch.h:2207:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:26:5: error: invalid token in expression
    expect_true((2 - 2) == 0);
    ^
../inst/include/./testthat/testthat.h:175:22: note: expanded from macro 'expect_true'
# define expect_true CATCH_CHECK
                     ^
../inst/include/./testthat/vendor/catch.h:11377:29: note: expanded from macro 'CATCH_CHECK'
#define CATCH_CHECK( expr ) INTERNAL_CATCH_TEST( "CATCH_CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
                            ^
../inst/include/./testthat/vendor/catch.h:2207:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:26:5: error: invalid operand
    expect_true((2 - 2) == 0);
    ^
../inst/include/./testthat/testthat.h:175:22: note: expanded from macro 'expect_true'
# define expect_true CATCH_CHECK
                     ^
../inst/include/./testthat/vendor/catch.h:11377:29: note: expanded from macro 'CATCH_CHECK'
#define CATCH_CHECK( expr ) INTERNAL_CATCH_TEST( "CATCH_CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
                            ^
../inst/include/./testthat/vendor/catch.h:2207:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:30:5: error: invalid token in expression
    expect_true((-1 < 0));
    ^
../inst/include/./testthat/testthat.h:175:22: note: expanded from macro 'expect_true'
# define expect_true CATCH_CHECK
                     ^
../inst/include/./testthat/vendor/catch.h:11377:29: note: expanded from macro 'CATCH_CHECK'
#define CATCH_CHECK( expr ) INTERNAL_CATCH_TEST( "CATCH_CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
                            ^
../inst/include/./testthat/vendor/catch.h:2207:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:30:5: error: invalid operand
    expect_true((-1 < 0));
    ^
../inst/include/./testthat/testthat.h:175:22: note: expanded from macro 'expect_true'
# define expect_true CATCH_CHECK
                     ^
../inst/include/./testthat/vendor/catch.h:11377:29: note: expanded from macro 'CATCH_CHECK'
#define CATCH_CHECK( expr ) INTERNAL_CATCH_TEST( "CATCH_CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
                            ^
../inst/include/./testthat/vendor/catch.h:2207:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:46:5: error: invalid token in expression
    expect_true(compiling_testthat);
    ^
../inst/include/./testthat/testthat.h:175:22: note: expanded from macro 'expect_true'
# define expect_true CATCH_CHECK
                     ^
../inst/include/./testthat/vendor/catch.h:11377:29: note: expanded from macro 'CATCH_CHECK'
#define CATCH_CHECK( expr ) INTERNAL_CATCH_TEST( "CATCH_CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
                            ^
../inst/include/./testthat/vendor/catch.h:2207:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:46:5: error: invalid operand
    expect_true(compiling_testthat);
    ^
../inst/include/./testthat/testthat.h:175:22: note: expanded from macro 'expect_true'
# define expect_true CATCH_CHECK
                     ^
../inst/include/./testthat/vendor/catch.h:11377:29: note: expanded from macro 'CATCH_CHECK'
#define CATCH_CHECK( expr ) INTERNAL_CATCH_TEST( "CATCH_CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
                            ^
../inst/include/./testthat/vendor/catch.h:2207:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:55:5: error: invalid token in expression
    expect_error(ouch());
    ^
../inst/include/./testthat/testthat.h:177:23: note: expanded from macro 'expect_error'
# define expect_error CATCH_CHECK_THROWS
                      ^
../inst/include/./testthat/vendor/catch.h:11383:37: note: expanded from macro 'CATCH_CHECK_THROWS'
#define CATCH_CHECK_THROWS( expr )  INTERNAL_CATCH_THROWS( "CATCH_CHECK_THROWS", Catch::ResultDisposition::ContinueOnFailure, "", expr )
                                    ^
../inst/include/./testthat/vendor/catch.h:2249:9: note: expanded from macro 'INTERNAL_CATCH_THROWS'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:55:5: error: invalid operand
    expect_error(ouch());
    ^
../inst/include/./testthat/testthat.h:177:23: note: expanded from macro 'expect_error'
# define expect_error CATCH_CHECK_THROWS
                      ^
../inst/include/./testthat/vendor/catch.h:11383:37: note: expanded from macro 'CATCH_CHECK_THROWS'
#define CATCH_CHECK_THROWS( expr )  INTERNAL_CATCH_THROWS( "CATCH_CHECK_THROWS", Catch::ResultDisposition::ContinueOnFailure, "", expr )
                                    ^
../inst/include/./testthat/vendor/catch.h:2249:9: note: expanded from macro 'INTERNAL_CATCH_THROWS'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:56:5: error: invalid token in expression
    expect_error_as(ouch(), std::exception);
    ^
../inst/include/./testthat/testthat.h:178:26: note: expanded from macro 'expect_error_as'
# define expect_error_as CATCH_CHECK_THROWS_AS
                         ^
../inst/include/./testthat/vendor/catch.h:11384:54: note: expanded from macro 'CATCH_CHECK_THROWS_AS'
#define CATCH_CHECK_THROWS_AS( expr, exceptionType ) INTERNAL_CATCH_THROWS_AS( "CATCH_CHECK_THROWS_AS", exceptionType, Catch::ResultDisposi...
                                                     ^
../inst/include/./testthat/vendor/catch.h:2269:9: note: expanded from macro 'INTERNAL_CATCH_THROWS_AS'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:56:5: error: invalid operand
    expect_error_as(ouch(), std::exception);
    ^
../inst/include/./testthat/testthat.h:178:26: note: expanded from macro 'expect_error_as'
# define expect_error_as CATCH_CHECK_THROWS_AS
                         ^
../inst/include/./testthat/vendor/catch.h:11384:54: note: expanded from macro 'CATCH_CHECK_THROWS_AS'
#define CATCH_CHECK_THROWS_AS( expr, exceptionType ) INTERNAL_CATCH_THROWS_AS( "CATCH_CHECK_THROWS_AS", exceptionType, Catch::ResultDisposi...
                                                     ^
../inst/include/./testthat/vendor/catch.h:2269:9: note: expanded from macro 'INTERNAL_CATCH_THROWS_AS'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:57:5: error: invalid token in expression
    expect_error_as(ouch(), std::logic_error);
    ^
../inst/include/./testthat/testthat.h:178:26: note: expanded from macro 'expect_error_as'
# define expect_error_as CATCH_CHECK_THROWS_AS
                         ^
../inst/include/./testthat/vendor/catch.h:11384:54: note: expanded from macro 'CATCH_CHECK_THROWS_AS'
#define CATCH_CHECK_THROWS_AS( expr, exceptionType ) INTERNAL_CATCH_THROWS_AS( "CATCH_CHECK_THROWS_AS", exceptionType, Catch::ResultDisposi...
                                                     ^
../inst/include/./testthat/vendor/catch.h:2269:9: note: expanded from macro 'INTERNAL_CATCH_THROWS_AS'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
test-catch.cpp:57:5: error: invalid operand
    expect_error_as(ouch(), std::logic_error);
    ^
../inst/include/./testthat/testthat.h:178:26: note: expanded from macro 'expect_error_as'
# define expect_error_as CATCH_CHECK_THROWS_AS
                         ^
../inst/include/./testthat/vendor/catch.h:11384:54: note: expanded from macro 'CATCH_CHECK_THROWS_AS'
#define CATCH_CHECK_THROWS_AS( expr, exceptionType ) INTERNAL_CATCH_THROWS_AS( "CATCH_CHECK_THROWS_AS", exceptionType, Catch::ResultDisposi...
                                                     ^
../inst/include/./testthat/vendor/catch.h:2269:9: note: expanded from macro 'INTERNAL_CATCH_THROWS_AS'
        INTERNAL_CATCH_REACT( __catchResult ) \
        ^
../inst/include/./testthat/vendor/catch.h:2191:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
    if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
                                           ^
../inst/include/./testthat/vendor/catch.h:2133:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
../inst/include/./testthat/vendor/catch.h:2111:38: note: expanded from macro 'CATCH_TRAP'
        #define CATCH_TRAP() __asm__("int $3\n" : : )
                                     ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
14 errors generated.
make: *** [test-catch.o] Error 1
ERROR: compilation failed for package ‘testthat’
* removing ‘/Users/isong/Library/R/4.0/library/testthat’
Warning message:
In install.packages("/Users/isong/Downloads/testthat", repos = NULL,  :
  installation of package ‘/Users/isong/Downloads/testthat’ had non-zero exit status
```

My system info is:
```> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: arm-apple-darwin20.1.0 (64-bit)
Running under: macOS Big Sur 11.0.1

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.dylib
LAPACK: /usr/local/lib/R/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    
```

Thank you!

**Comment by kevinushey** [comment] 2020-11-24 18:07
What version of `g++` are you using?

**Comment by gaborcsardi** [comment] 2020-11-24 18:12
> ```
> Platform: arm-apple-darwin20.1.0 (64-bit)
> ```

Also, is this Rosetta and R is mis-reporting the platform? Or an actual Apple Silicon build of R?

**Comment by sigmafelix** [comment] 2020-11-24 18:15
@kevinushey  
```
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: arm64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
@gaborcsardi I tried building the native build of R on my Mac machine with Apple Silicon. I am currently testing various R packages to build on the Apple Silicon-based system.

Thank you!

**Comment by gaborcsardi** [comment] 2020-11-24 19:26
If this is indeed arm and not Rosetta, then to reproduce it we'd need an R build for M1, which is not trivial. Can you share yours?

**Comment by sigmafelix** [comment] 2020-11-24 21:44
@gaborcsardi Here is the OneDrive link for the R build on Apple Silicon: [Link](https://1drv.ms/u/s!AkpBA_t8nruRgdV9LgZxU3HP4o6ouA?e=mdF1H1).

**Comment by tzakharko** [comment] 2020-11-25 09:06
@gaborcsardi @sigmafelix I have a native R build on M1, please feel free to ping me if you need any assistance on this (or any other M1-related testing). From what I see the problem is that testthat uses a very old version of catch. Apparently [this](https://github.com/catchorg/Catch2/pull/1084) change fixes catch platform detection. But I have no idea if testthat is compatible with newer catch headers, will try it out later.

**Comment by tzakharko** [comment] 2020-11-25 09:13
I simply installed the pre-build package kindly provided by fxcoudert (https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11-arm-alpha1)

**Comment by tzakharko** [comment] 2020-11-25 10:19
I have just pushed a fix, see https://github.com/r-lib/testthat/pull/1246

**Comment by sigmafelix** [comment] 2020-11-25 20:43
@tzakharko Thank you for the fix! It works smoothly on my machine.

**Closed** 2020-11-27 15:10 UTC
