### ISSUE TITLE
No colors in test active file output

### ISSUE THREAD

**Issue by olivroy** [r-lib/testthat#1846] opened 2023-08-10 13:13 UTC
Is there anything testthat can do about rstudio/rstudio#13088

If I use Ctrl + Shift + T, to test, everything works as expected. (Colored output and clickable hyperlink)

However, if I use the Run Tests button to run tests in the active file, there are no colors or hyperlinks in the Build Pane.
![image](https://github.com/r-lib/testthat/assets/52606734/cb3fac55-f634-48e1-8ed1-d744eccde0fc)

This would be helpful for this to work, as running all tests is long for all packages. 

I think it would be neat to have this colored output, especially as it is advertised in R packages https://r-pkgs.org/testing-basics.html#run-tests (the RStudio box)

I only see this on Windows (not on Mac)

**Comment by hadley** [comment] 2023-09-22 15:51
Duplicate of #1561

**Closed by hadley** 2023-09-22 15:51 UTC
