### ISSUE TITLE
test_examples says it skipped Rd files which do contain example code

### ISSUE THREAD

**Issue by jackwasey** [r-lib/testthat#740] opened 2018-04-03 23:11 UTC
It appears that almost all examples in my roxygen2 generated Rd files are marked as 'skipped' by `test_examples`. By chance, I had some function examples which produced some kind of legitimate output (not by 'print' or 'cat'), and these were handled by the message handler in `testthat:::test_code`.

To reproduce:
1. get the devtools source tree
2. add a file in `tests/testthat/test-skipbug.R` containing:
> context("skipbug")
> test_examples()
3. devtools::test(filter="skipbug")
4. note the following:
> ???: skip: /usr/local/src/git/devtools/man/session_info.Rd
> Empty test
5. note that man/session_info.Rd contains:
> examples{
> session_info()
> session_info("devtools")
> }

Expected result: passed test for session_info.Rd, and for many other functions with example code which is not surrounded by dontrun or donttest.

Inserting `message("anything")` causes an example to be 'handled' and thus pass the test.

 > testthat       * 2.0.0   2017-12-13 CRAN (R 3.4.3)

**Comment by nteetor** [comment] 2018-11-30 18:31
This is also the case for `test_example()`. I would love to no longer see "Empty test" printed for successfully run examples and am happy to work on this issue. However, I have not previously contributed to testthat. How might this problem be approached? Could it be enough to set `skip_on_empty` to `FALSE` in `test_example()`'s call to `test_code()`?

https://github.com/r-lib/testthat/blob/8216ebe2d84028d1a7a315c5c17c15f93cad3d65/R/test-example.R#L52

Setting `skip_on_empty` to `FALSE` would avoid the, currently default, call to `skip_empty()` in `test_code()`, but I imagine there are undesired consequences I am unaware of.

**Comment by hadley** [comment] 2019-03-28 22:44
Duplicate of #841

**Closed by hadley** 2019-03-28 22:44 UTC
Labels: bug
