### ISSUE TITLE
max.print in expect_snapshot

### ISSUE THREAD

**Issue by arnaud-feldmann** [r-lib/testthat#1428] opened 2021-08-22 10:22 UTC
```
test_that("maxprint", {
  expect_snapshot(cbind(a=1:1000,b=1:1000))
})
```

If this is run through RStudio **CTRL+MAJ+T**, this test doesn't make the same snapshot as if run with `devtools::test` in the console, because of the `max.print` that defaults at 1000. I may be wrong but this is a bit disturbing, as typically I think `expect_snapshot` is used to test the object, not the printing system. Hence I think one doesn't expect that `expect_snapshot` to be impacted by the maxprint option. Maybe the non-output snapshots should always ignore `max.print` ?

**EDIT :** I've seen this post https://github.com/r-lib/testthat/issues/1367#issue-858456686 by @krlmlr .  I think, either the `max.print` option is available, either it should be set to 99999 even in `devtool::test` ? Maybe i make a mistake about the purpose of `expect_snapshot` and my understanding of it is closer to `expect_snapshot_value` ?

**Comment by hadley** [comment] 2021-09-10 17:32
Duplicate of #1367

**Closed by hadley** 2021-09-10 17:32 UTC
