### ISSUE TITLE
Object comparison is painfully unhelpful

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/testthat#852] opened 2019-03-07 20:08 UTC
First a prelude so this doesn’t come over wrong: I love testthat, life would be much much harder. Thank you. I’ve been happy to see it improve a lot over the years!

However, one part always stayed kinda lacking: Object comparison is  `expect_identical` and friends. E.g. If I pass in two vectors, with one lacking an element somewhere, `expect_identical` just tells me that the lengths are different, not which element(s) is/are actually missing/superfluous.

I found the diffobj library and wrote a quick replacement just to get a goo string diff, which works *really* beautifully (diffobj has more functions for other data types):

```r
expect_no_diff <- function(object, expected) {
    one_element <- length(object) == 1L && length(expected) == 1L
    if (one_element) {  # if we pass a 1-element string vector with '\n's
        object   <- strsplit(object,   '\n')[[1]]
        expected <- strsplit(expected, '\n')[[1]]
    }
    dif <- diffobj::diffChr(
        object, expected,
        format = 'ansi256',  # should probably be set depending on checks testthat already does
        ignore.white.space = FALSE,  # the docs say FALSE is the default but that’s a lie
        interactive = FALSE)  # necessary, else a pager plops up
    expect(!any(dif), as.character(dif))
}
```

It would be very useful to have that in testthat by default, the current output is leagues behind pytest and friends. This is the result. Note how it adapts to the width of the RStudio test output panel!

![grafik](https://user-images.githubusercontent.com/291575/53985909-1beec280-411d-11e9-8793-da1766b58531.png)

**Comment by hadley** [comment] 2019-03-28 14:36
Basically a duplicate of #447 — I agree that we need to either do more in testthat or call out to another package.

**Closed by hadley** 2019-03-28 14:36 UTC
